spring:
  application:
    name: seosanbook

  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3307/seosanbook?characterEncoding=UTF8&serverTimezone=Asia/Seoul
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 1234

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never  # ? ?? ? SPRING_SESSION ??? ?? ??

mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    org.mybatis: DEBUG
    hackerton.seosanbook.mappers: DEBUG


jwt:
  secret: "f9v82GmhnmOpwHKReppWJem8ZnOJ1/tOOtnFT48t7OA=" # ?? 32? ??